### PR TITLE
perl5.18+ support

### PR DESCRIPTION
**Pull request by markwellis**
upgraded picohttpparser and M::I::XSUtil version requirement

i've also updated Changes and called it version 0.04

### CODE REVIEW

**Comment by tokuhirom** [comment]
:+1:

**Comment by markwellis** [comment]
any chance on merging and releasing this @mala, or if you have no time/energy you can give me comaint and I'll do it?

**Comment by markwellis** [comment]
bump

**Comment by markwellis** [comment]
ping

**Pull request closed without merging**
